# Basic Site Information
name: Israel Morales Marin
description: Web Developer from St. Petersburg, Florida
avatar: https://raw.githubusercontent.com/barryclark/jekyll-now/master/images/jekyll-logo.png
url: "" # Set your site URL if needed (e.g., "https://yourusername.github.io")
baseurl: "" # If hosted in a repository (e.g., /repository-name)

# Site Navigation and Permalinks
permalink: /:categories/:title/
relative_permalinks: false

# Social Links (Add your own usernames)
footer-links:
  dribbble:
  email:
  facebook:
  flickr:
  github: 
  instagram:
  linkedin:
  pinterest:
  rss: # just type anything here for a working RSS icon
  twitter: jekyllrb
  stackoverflow: 
  youtube:
  googleplus:

# Collections for Each Tutorial Topic
collections:
  css:
    output: true
    permalink: /css/:path/
  javascript:
    output: true
    permalink: /javascript/:path/
  python:
    output: true
    permalink: /python/:path/
  herramientas:
    output: true
    permalink: /herramientas/:path/

# Disqus for Comments (if using Disqus)
disqus: # Add your Disqus shortname here

# Google Analytics (for tracking, optional)
google_analytics: # Add your Google Analytics tracking code here

# Markdown and Syntax Highlighting
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

# Jekyll Plugins
plugins:
  - jekyll-sitemap  # Generates a sitemap
  - jekyll-feed     # Generates an Atom feed

# Exclusions (files not to include in the generated site)
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

# Versioning (Optional, for tracking which Jekyll Now version you are using)
version: v1.2.0
